// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ojq_o3Sa7ReqtNVkrdjq4RtRionOZhI',
    appId: '1:1098479704033:web:b92c697df28d99db5fa4a0',
    messagingSenderId: '1098479704033',
    projectId: 'cat-23',
    authDomain: 'cat-23.firebaseapp.com',
    storageBucket: 'cat-23.appspot.com',
    measurementId: 'G-758FCCE7NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSPZ5LVNyYNVjHjMDVwuKVS2j2bzmBFXQ',
    appId: '1:1098479704033:android:aa918f1d575a80745fa4a0',
    messagingSenderId: '1098479704033',
    projectId: 'cat-23',
    storageBucket: 'cat-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQkuYVSSVuo4594ope3qiYMYgUdamfDIE',
    appId: '1:1098479704033:ios:6301d504ac53e0dc5fa4a0',
    messagingSenderId: '1098479704033',
    projectId: 'cat-23',
    storageBucket: 'cat-23.appspot.com',
    iosBundleId: 'com.example.cat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQkuYVSSVuo4594ope3qiYMYgUdamfDIE',
    appId: '1:1098479704033:ios:8bcddf8870d8bac75fa4a0',
    messagingSenderId: '1098479704033',
    projectId: 'cat-23',
    storageBucket: 'cat-23.appspot.com',
    iosBundleId: 'com.example.cat.RunnerTests',
  );
}
